/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IOC_RPC_H_RPCGEN
#define _IOC_RPC_H_RPCGEN

#include <rpc/rpc.h>


struct address {
	u_int addr;
	u_int data;
};
typedef struct address address;
#ifdef __cplusplus 
extern "C" bool_t xdr_address(XDR *, address*);
#elif __STDC__ 
extern  bool_t xdr_address(XDR *, address*);
#else /* Old Style C */ 
bool_t xdr_address();
#endif /* Old Style C */ 


struct vpg {
	char *patname;
	u_int divider;
	u_int delay15;
	u_int delay16;
	u_int addr;
	u_int data;
};
typedef struct vpg vpg;
#ifdef __cplusplus 
extern "C" bool_t xdr_vpg(XDR *, vpg*);
#elif __STDC__ 
extern  bool_t xdr_vpg(XDR *, vpg*);
#else /* Old Style C */ 
bool_t xdr_vpg();
#endif /* Old Style C */ 


struct detector {
	char *fname;
	u_int module;
	u_int chip;
	u_int strip;
	u_int data;
};
typedef struct detector detector;
#ifdef __cplusplus 
extern "C" bool_t xdr_detector(XDR *, detector*);
#elif __STDC__ 
extern  bool_t xdr_detector(XDR *, detector*);
#else /* Old Style C */ 
bool_t xdr_detector();
#endif /* Old Style C */ 


struct image {
	int npix;
	struct {
		u_int img_len;
		u_int *img_val;
	} img;
};
typedef struct image image;
#ifdef __cplusplus 
extern "C" bool_t xdr_image(XDR *, image*);
#elif __STDC__ 
extern  bool_t xdr_image(XDR *, image*);
#else /* Old Style C */ 
bool_t xdr_image();
#endif /* Old Style C */ 


struct arry {
	struct {
		u_int data_len;
		u_int *data_val;
	} data;
};
typedef struct arry arry;
#ifdef __cplusplus 
extern "C" bool_t xdr_arry(XDR *, arry*);
#elif __STDC__ 
extern  bool_t xdr_arry(XDR *, arry*);
#else /* Old Style C */ 
bool_t xdr_arry();
#endif /* Old Style C */ 


struct image_spec {
	char *patname;
	struct {
		u_int data_len;
		u_int *data_val;
	} data;
	u_int mode;
};
typedef struct image_spec image_spec;
#ifdef __cplusplus 
extern "C" bool_t xdr_image_spec(XDR *, image_spec*);
#elif __STDC__ 
extern  bool_t xdr_image_spec(XDR *, image_spec*);
#else /* Old Style C */ 
bool_t xdr_image_spec();
#endif /* Old Style C */ 


struct n_image_spec {
	char *patname;
	struct {
		u_int data_len;
		u_int *data_val;
	} data;
	u_int nimg;
	u_int etime;
};
typedef struct n_image_spec n_image_spec;
#ifdef __cplusplus 
extern "C" bool_t xdr_n_image_spec(XDR *, n_image_spec*);
#elif __STDC__ 
extern  bool_t xdr_n_image_spec(XDR *, n_image_spec*);
#else /* Old Style C */ 
bool_t xdr_n_image_spec();
#endif /* Old Style C */ 


#define rpcfns ((u_long)10071971)
#define TWO ((u_long)2)

#ifdef __cplusplus
#define rpc_vpg_write_a32 ((u_long)1)
extern "C" int * rpc_vpg_write_a32_2(address *, CLIENT *);
extern "C" int * rpc_vpg_write_a32_2_svc(address *, struct svc_req *);
#define rpc_vpg_read_a32 ((u_long)2)
extern "C" int * rpc_vpg_read_a32_2(address *, CLIENT *);
extern "C" int * rpc_vpg_read_a32_2_svc(address *, struct svc_req *);
#define rpc_vpg_set_clk_divider ((u_long)3)
extern "C" int * rpc_vpg_set_clk_divider_2(vpg *, CLIENT *);
extern "C" int * rpc_vpg_set_clk_divider_2_svc(vpg *, struct svc_req *);
#define rpc_vpg_set_clk_delay ((u_long)4)
extern "C" int * rpc_vpg_set_clk_delay_2(vpg *, CLIENT *);
extern "C" int * rpc_vpg_set_clk_delay_2_svc(vpg *, struct svc_req *);
#define rpc_vpg_write_output ((u_long)5)
extern "C" int * rpc_vpg_write_output_2(vpg *, CLIENT *);
extern "C" int * rpc_vpg_write_output_2_svc(vpg *, struct svc_req *);
#define rpc_vpg_read_input ((u_long)6)
extern "C" int * rpc_vpg_read_input_2(void *, CLIENT *);
extern "C" int * rpc_vpg_read_input_2_svc(void *, struct svc_req *);
#define rpc_vpg_loadpattern ((u_long)7)
extern "C" int * rpc_vpg_loadpattern_2(vpg *, CLIENT *);
extern "C" int * rpc_vpg_loadpattern_2_svc(vpg *, struct svc_req *);
#define rpc_vpg_jump ((u_long)8)
extern "C" int * rpc_vpg_jump_2(vpg *, CLIENT *);
extern "C" int * rpc_vpg_jump_2_svc(vpg *, struct svc_req *);
#define rpc_vpg_clk ((u_long)9)
extern "C" int * rpc_vpg_clk_2(void *, CLIENT *);
extern "C" int * rpc_vpg_clk_2_svc(void *, struct svc_req *);
#define rpc_vpg_write_status ((u_long)10)
extern "C" int * rpc_vpg_write_status_2(vpg *, CLIENT *);
extern "C" int * rpc_vpg_write_status_2_svc(vpg *, struct svc_req *);
#define rpc_vpg_read_status ((u_long)11)
extern "C" int * rpc_vpg_read_status_2(void *, CLIENT *);
extern "C" int * rpc_vpg_read_status_2_svc(void *, struct svc_req *);
#define rpc_vpg_set_force ((u_long)12)
extern "C" int * rpc_vpg_set_force_2(vpg *, CLIENT *);
extern "C" int * rpc_vpg_set_force_2_svc(vpg *, struct svc_req *);
#define rpc_vpg_clk_start ((u_long)13)
extern "C" int * rpc_vpg_clk_start_2(void *, CLIENT *);
extern "C" int * rpc_vpg_clk_start_2_svc(void *, struct svc_req *);
#define rpc_vpg_clk_stop ((u_long)14)
extern "C" int * rpc_vpg_clk_stop_2(void *, CLIENT *);
extern "C" int * rpc_vpg_clk_stop_2_svc(void *, struct svc_req *);
#define rpc_vpg_pc_reset ((u_long)15)
extern "C" int * rpc_vpg_pc_reset_2(void *, CLIENT *);
extern "C" int * rpc_vpg_pc_reset_2_svc(void *, struct svc_req *);
#define rpc_vpg_clr_mem ((u_long)16)
extern "C" int * rpc_vpg_clr_mem_2(void *, CLIENT *);
extern "C" int * rpc_vpg_clr_mem_2_svc(void *, struct svc_req *);
#define rpc_vpg_vpgini ((u_long)17)
extern "C" int * rpc_vpg_vpgini_2(void *, CLIENT *);
extern "C" int * rpc_vpg_vpgini_2_svc(void *, struct svc_req *);
#define rpc_fifo_read_d32 ((u_long)50)
extern "C" int * rpc_fifo_read_d32_2(address *, CLIENT *);
extern "C" int * rpc_fifo_read_d32_2_svc(address *, struct svc_req *);
#define rpc_fifo_write_d32 ((u_long)51)
extern "C" int * rpc_fifo_write_d32_2(address *, CLIENT *);
extern "C" int * rpc_fifo_write_d32_2_svc(address *, struct svc_req *);
#define rpc_fifo_fifoini ((u_long)52)
extern "C" int * rpc_fifo_fifoini_2(void *, CLIENT *);
extern "C" int * rpc_fifo_fifoini_2_svc(void *, struct svc_req *);
#define rpc_fifo_read_data ((u_long)53)
extern "C" int * rpc_fifo_read_data_2(address *, CLIENT *);
extern "C" int * rpc_fifo_read_data_2_svc(address *, struct svc_req *);
#define rpc_fifo_read_event_cntr ((u_long)54)
extern "C" int * rpc_fifo_read_event_cntr_2(address *, CLIENT *);
extern "C" int * rpc_fifo_read_event_cntr_2_svc(address *, struct svc_req *);
#define rpc_fifo_read_status ((u_long)55)
extern "C" int * rpc_fifo_read_status_2(address *, CLIENT *);
extern "C" int * rpc_fifo_read_status_2_svc(address *, struct svc_req *);
#define rpc_fifo_write_data ((u_long)56)
extern "C" int * rpc_fifo_write_data_2(address *, CLIENT *);
extern "C" int * rpc_fifo_write_data_2_svc(address *, struct svc_req *);
#define rpc_fifo_write_control ((u_long)57)
extern "C" int * rpc_fifo_write_control_2(address *, CLIENT *);
extern "C" int * rpc_fifo_write_control_2_svc(address *, struct svc_req *);
#define rpc_fifo_write_test ((u_long)58)
extern "C" int * rpc_fifo_write_test_2(address *, CLIENT *);
extern "C" int * rpc_fifo_write_test_2_svc(address *, struct svc_req *);
#define rpc_sd_selectmodule ((u_long)101)
extern "C" int * rpc_sd_selectmodule_2(detector *, CLIENT *);
extern "C" int * rpc_sd_selectmodule_2_svc(detector *, struct svc_req *);
#define rpc_sd_selectchip ((u_long)102)
extern "C" int * rpc_sd_selectchip_2(detector *, CLIENT *);
extern "C" int * rpc_sd_selectchip_2_svc(detector *, struct svc_req *);
#define rpc_sd_selectstrip ((u_long)103)
extern "C" int * rpc_sd_selectstrip_2(detector *, CLIENT *);
extern "C" int * rpc_sd_selectstrip_2_svc(detector *, struct svc_req *);
#define rpc_sd_setdac ((u_long)104)
extern "C" int * rpc_sd_setdac_2(detector *, CLIENT *);
extern "C" int * rpc_sd_setdac_2_svc(detector *, struct svc_req *);
#define rpc_sd_reset ((u_long)105)
extern "C" int * rpc_sd_reset_2(detector *, CLIENT *);
extern "C" int * rpc_sd_reset_2_svc(detector *, struct svc_req *);
#define rpc_sd_readmodule ((u_long)106)
extern "C" int * rpc_sd_readmodule_2(detector *, CLIENT *);
extern "C" int * rpc_sd_readmodule_2_svc(detector *, struct svc_req *);
#define rpc_sd_readdet ((u_long)107)
extern "C" int * rpc_sd_readdet_2(detector *, CLIENT *);
extern "C" int * rpc_sd_readdet_2_svc(detector *, struct svc_req *);
#define rpc_sd_testFPGA ((u_long)108)
extern "C" int * rpc_sd_testfpga_2(detector *, CLIENT *);
extern "C" int * rpc_sd_testfpga_2_svc(detector *, struct svc_req *);
#define rpc_sd_teststshift ((u_long)109)
extern "C" int * rpc_sd_teststshift_2(detector *, CLIENT *);
extern "C" int * rpc_sd_teststshift_2_svc(detector *, struct svc_req *);
#define rpc_sd_testdtshift ((u_long)110)
extern "C" int * rpc_sd_testdtshift_2(detector *, CLIENT *);
extern "C" int * rpc_sd_testdtshift_2_svc(detector *, struct svc_req *);
#define rpc_sd_settrimbits ((u_long)111)
extern "C" int * rpc_sd_settrimbits_2(detector *, CLIENT *);
extern "C" int * rpc_sd_settrimbits_2_svc(detector *, struct svc_req *);
#define rpc_sd_initdet ((u_long)112)
extern "C" int * rpc_sd_initdet_2(detector *, CLIENT *);
extern "C" int * rpc_sd_initdet_2_svc(detector *, struct svc_req *);
#define rpc_sd_writest ((u_long)113)
extern "C" int * rpc_sd_writest_2(detector *, CLIENT *);
extern "C" int * rpc_sd_writest_2_svc(detector *, struct svc_req *);
#define rpc_sd_readst ((u_long)114)
extern "C" int * rpc_sd_readst_2(detector *, CLIENT *);
extern "C" int * rpc_sd_readst_2_svc(detector *, struct svc_req *);
#define rpc_sd_writedt ((u_long)115)
extern "C" int * rpc_sd_writedt_2(detector *, CLIENT *);
extern "C" int * rpc_sd_writedt_2_svc(detector *, struct svc_req *);
#define rpc_sd_readdt ((u_long)116)
extern "C" int * rpc_sd_readdt_2(detector *, CLIENT *);
extern "C" int * rpc_sd_readdt_2_svc(detector *, struct svc_req *);
#define rpc_sd_writemodFPGA ((u_long)117)
extern "C" int * rpc_sd_writemodfpga_2(detector *, CLIENT *);
extern "C" int * rpc_sd_writemodfpga_2_svc(detector *, struct svc_req *);
#define rpc_sd_readmodFPGA ((u_long)118)
extern "C" int * rpc_sd_readmodfpga_2(detector *, CLIENT *);
extern "C" int * rpc_sd_readmodfpga_2_svc(detector *, struct svc_req *);
#define rpc_sd_writedetFPGA ((u_long)119)
extern "C" int * rpc_sd_writedetfpga_2(detector *, CLIENT *);
extern "C" int * rpc_sd_writedetfpga_2_svc(detector *, struct svc_req *);
#define rpc_sd_readdetFPGA ((u_long)120)
extern "C" int * rpc_sd_readdetfpga_2(detector *, CLIENT *);
extern "C" int * rpc_sd_readdetfpga_2_svc(detector *, struct svc_req *);
#define rpc_px_read_image ((u_long)200)
extern "C" image * rpc_px_read_image_2(void *, CLIENT *);
extern "C" image * rpc_px_read_image_2_svc(void *, struct svc_req *);
#define rpc_px_set_selector ((u_long)201)
extern "C" int * rpc_px_set_selector_2(arry *, CLIENT *);
extern "C" int * rpc_px_set_selector_2_svc(arry *, struct svc_req *);
#define rpc_vpg_set_default ((u_long)202)
extern "C" int * rpc_vpg_set_default_2(int *, CLIENT *);
extern "C" int * rpc_vpg_set_default_2_svc(int *, struct svc_req *);
#define rpc_fifo_write_image ((u_long)203)
extern "C" int * rpc_fifo_write_image_2(image_spec *, CLIENT *);
extern "C" int * rpc_fifo_write_image_2_svc(image_spec *, struct svc_req *);
#define rpc_fifo_write_n_images ((u_long)204)
extern "C" int * rpc_fifo_write_n_images_2(n_image_spec *, CLIENT *);
extern "C" int * rpc_fifo_write_n_images_2_svc(n_image_spec *, struct svc_req *);
#define rpc_fifo_set_level ((u_long)205)
extern "C" int * rpc_fifo_set_level_2(int *, CLIENT *);
extern "C" int * rpc_fifo_set_level_2_svc(int *, struct svc_req *);

#elif __STDC__
#define rpc_vpg_write_a32 ((u_long)1)
extern  int * rpc_vpg_write_a32_2(address *, CLIENT *);
extern  int * rpc_vpg_write_a32_2_svc(address *, struct svc_req *);
#define rpc_vpg_read_a32 ((u_long)2)
extern  int * rpc_vpg_read_a32_2(address *, CLIENT *);
extern  int * rpc_vpg_read_a32_2_svc(address *, struct svc_req *);
#define rpc_vpg_set_clk_divider ((u_long)3)
extern  int * rpc_vpg_set_clk_divider_2(vpg *, CLIENT *);
extern  int * rpc_vpg_set_clk_divider_2_svc(vpg *, struct svc_req *);
#define rpc_vpg_set_clk_delay ((u_long)4)
extern  int * rpc_vpg_set_clk_delay_2(vpg *, CLIENT *);
extern  int * rpc_vpg_set_clk_delay_2_svc(vpg *, struct svc_req *);
#define rpc_vpg_write_output ((u_long)5)
extern  int * rpc_vpg_write_output_2(vpg *, CLIENT *);
extern  int * rpc_vpg_write_output_2_svc(vpg *, struct svc_req *);
#define rpc_vpg_read_input ((u_long)6)
extern  int * rpc_vpg_read_input_2(void *, CLIENT *);
extern  int * rpc_vpg_read_input_2_svc(void *, struct svc_req *);
#define rpc_vpg_loadpattern ((u_long)7)
extern  int * rpc_vpg_loadpattern_2(vpg *, CLIENT *);
extern  int * rpc_vpg_loadpattern_2_svc(vpg *, struct svc_req *);
#define rpc_vpg_jump ((u_long)8)
extern  int * rpc_vpg_jump_2(vpg *, CLIENT *);
extern  int * rpc_vpg_jump_2_svc(vpg *, struct svc_req *);
#define rpc_vpg_clk ((u_long)9)
extern  int * rpc_vpg_clk_2(void *, CLIENT *);
extern  int * rpc_vpg_clk_2_svc(void *, struct svc_req *);
#define rpc_vpg_write_status ((u_long)10)
extern  int * rpc_vpg_write_status_2(vpg *, CLIENT *);
extern  int * rpc_vpg_write_status_2_svc(vpg *, struct svc_req *);
#define rpc_vpg_read_status ((u_long)11)
extern  int * rpc_vpg_read_status_2(void *, CLIENT *);
extern  int * rpc_vpg_read_status_2_svc(void *, struct svc_req *);
#define rpc_vpg_set_force ((u_long)12)
extern  int * rpc_vpg_set_force_2(vpg *, CLIENT *);
extern  int * rpc_vpg_set_force_2_svc(vpg *, struct svc_req *);
#define rpc_vpg_clk_start ((u_long)13)
extern  int * rpc_vpg_clk_start_2(void *, CLIENT *);
extern  int * rpc_vpg_clk_start_2_svc(void *, struct svc_req *);
#define rpc_vpg_clk_stop ((u_long)14)
extern  int * rpc_vpg_clk_stop_2(void *, CLIENT *);
extern  int * rpc_vpg_clk_stop_2_svc(void *, struct svc_req *);
#define rpc_vpg_pc_reset ((u_long)15)
extern  int * rpc_vpg_pc_reset_2(void *, CLIENT *);
extern  int * rpc_vpg_pc_reset_2_svc(void *, struct svc_req *);
#define rpc_vpg_clr_mem ((u_long)16)
extern  int * rpc_vpg_clr_mem_2(void *, CLIENT *);
extern  int * rpc_vpg_clr_mem_2_svc(void *, struct svc_req *);
#define rpc_vpg_vpgini ((u_long)17)
extern  int * rpc_vpg_vpgini_2(void *, CLIENT *);
extern  int * rpc_vpg_vpgini_2_svc(void *, struct svc_req *);
#define rpc_fifo_read_d32 ((u_long)50)
extern  int * rpc_fifo_read_d32_2(address *, CLIENT *);
extern  int * rpc_fifo_read_d32_2_svc(address *, struct svc_req *);
#define rpc_fifo_write_d32 ((u_long)51)
extern  int * rpc_fifo_write_d32_2(address *, CLIENT *);
extern  int * rpc_fifo_write_d32_2_svc(address *, struct svc_req *);
#define rpc_fifo_fifoini ((u_long)52)
extern  int * rpc_fifo_fifoini_2(void *, CLIENT *);
extern  int * rpc_fifo_fifoini_2_svc(void *, struct svc_req *);
#define rpc_fifo_read_data ((u_long)53)
extern  int * rpc_fifo_read_data_2(address *, CLIENT *);
extern  int * rpc_fifo_read_data_2_svc(address *, struct svc_req *);
#define rpc_fifo_read_event_cntr ((u_long)54)
extern  int * rpc_fifo_read_event_cntr_2(address *, CLIENT *);
extern  int * rpc_fifo_read_event_cntr_2_svc(address *, struct svc_req *);
#define rpc_fifo_read_status ((u_long)55)
extern  int * rpc_fifo_read_status_2(address *, CLIENT *);
extern  int * rpc_fifo_read_status_2_svc(address *, struct svc_req *);
#define rpc_fifo_write_data ((u_long)56)
extern  int * rpc_fifo_write_data_2(address *, CLIENT *);
extern  int * rpc_fifo_write_data_2_svc(address *, struct svc_req *);
#define rpc_fifo_write_control ((u_long)57)
extern  int * rpc_fifo_write_control_2(address *, CLIENT *);
extern  int * rpc_fifo_write_control_2_svc(address *, struct svc_req *);
#define rpc_fifo_write_test ((u_long)58)
extern  int * rpc_fifo_write_test_2(address *, CLIENT *);
extern  int * rpc_fifo_write_test_2_svc(address *, struct svc_req *);
#define rpc_sd_selectmodule ((u_long)101)
extern  int * rpc_sd_selectmodule_2(detector *, CLIENT *);
extern  int * rpc_sd_selectmodule_2_svc(detector *, struct svc_req *);
#define rpc_sd_selectchip ((u_long)102)
extern  int * rpc_sd_selectchip_2(detector *, CLIENT *);
extern  int * rpc_sd_selectchip_2_svc(detector *, struct svc_req *);
#define rpc_sd_selectstrip ((u_long)103)
extern  int * rpc_sd_selectstrip_2(detector *, CLIENT *);
extern  int * rpc_sd_selectstrip_2_svc(detector *, struct svc_req *);
#define rpc_sd_setdac ((u_long)104)
extern  int * rpc_sd_setdac_2(detector *, CLIENT *);
extern  int * rpc_sd_setdac_2_svc(detector *, struct svc_req *);
#define rpc_sd_reset ((u_long)105)
extern  int * rpc_sd_reset_2(detector *, CLIENT *);
extern  int * rpc_sd_reset_2_svc(detector *, struct svc_req *);
#define rpc_sd_readmodule ((u_long)106)
extern  int * rpc_sd_readmodule_2(detector *, CLIENT *);
extern  int * rpc_sd_readmodule_2_svc(detector *, struct svc_req *);
#define rpc_sd_readdet ((u_long)107)
extern  int * rpc_sd_readdet_2(detector *, CLIENT *);
extern  int * rpc_sd_readdet_2_svc(detector *, struct svc_req *);
#define rpc_sd_testFPGA ((u_long)108)
extern  int * rpc_sd_testfpga_2(detector *, CLIENT *);
extern  int * rpc_sd_testfpga_2_svc(detector *, struct svc_req *);
#define rpc_sd_teststshift ((u_long)109)
extern  int * rpc_sd_teststshift_2(detector *, CLIENT *);
extern  int * rpc_sd_teststshift_2_svc(detector *, struct svc_req *);
#define rpc_sd_testdtshift ((u_long)110)
extern  int * rpc_sd_testdtshift_2(detector *, CLIENT *);
extern  int * rpc_sd_testdtshift_2_svc(detector *, struct svc_req *);
#define rpc_sd_settrimbits ((u_long)111)
extern  int * rpc_sd_settrimbits_2(detector *, CLIENT *);
extern  int * rpc_sd_settrimbits_2_svc(detector *, struct svc_req *);
#define rpc_sd_initdet ((u_long)112)
extern  int * rpc_sd_initdet_2(detector *, CLIENT *);
extern  int * rpc_sd_initdet_2_svc(detector *, struct svc_req *);
#define rpc_sd_writest ((u_long)113)
extern  int * rpc_sd_writest_2(detector *, CLIENT *);
extern  int * rpc_sd_writest_2_svc(detector *, struct svc_req *);
#define rpc_sd_readst ((u_long)114)
extern  int * rpc_sd_readst_2(detector *, CLIENT *);
extern  int * rpc_sd_readst_2_svc(detector *, struct svc_req *);
#define rpc_sd_writedt ((u_long)115)
extern  int * rpc_sd_writedt_2(detector *, CLIENT *);
extern  int * rpc_sd_writedt_2_svc(detector *, struct svc_req *);
#define rpc_sd_readdt ((u_long)116)
extern  int * rpc_sd_readdt_2(detector *, CLIENT *);
extern  int * rpc_sd_readdt_2_svc(detector *, struct svc_req *);
#define rpc_sd_writemodFPGA ((u_long)117)
extern  int * rpc_sd_writemodfpga_2(detector *, CLIENT *);
extern  int * rpc_sd_writemodfpga_2_svc(detector *, struct svc_req *);
#define rpc_sd_readmodFPGA ((u_long)118)
extern  int * rpc_sd_readmodfpga_2(detector *, CLIENT *);
extern  int * rpc_sd_readmodfpga_2_svc(detector *, struct svc_req *);
#define rpc_sd_writedetFPGA ((u_long)119)
extern  int * rpc_sd_writedetfpga_2(detector *, CLIENT *);
extern  int * rpc_sd_writedetfpga_2_svc(detector *, struct svc_req *);
#define rpc_sd_readdetFPGA ((u_long)120)
extern  int * rpc_sd_readdetfpga_2(detector *, CLIENT *);
extern  int * rpc_sd_readdetfpga_2_svc(detector *, struct svc_req *);
#define rpc_px_read_image ((u_long)200)
extern  image * rpc_px_read_image_2(void *, CLIENT *);
extern  image * rpc_px_read_image_2_svc(void *, struct svc_req *);
#define rpc_px_set_selector ((u_long)201)
extern  int * rpc_px_set_selector_2(arry *, CLIENT *);
extern  int * rpc_px_set_selector_2_svc(arry *, struct svc_req *);
#define rpc_vpg_set_default ((u_long)202)
extern  int * rpc_vpg_set_default_2(int *, CLIENT *);
extern  int * rpc_vpg_set_default_2_svc(int *, struct svc_req *);
#define rpc_fifo_write_image ((u_long)203)
extern  int * rpc_fifo_write_image_2(image_spec *, CLIENT *);
extern  int * rpc_fifo_write_image_2_svc(image_spec *, struct svc_req *);
#define rpc_fifo_write_n_images ((u_long)204)
extern  int * rpc_fifo_write_n_images_2(n_image_spec *, CLIENT *);
extern  int * rpc_fifo_write_n_images_2_svc(n_image_spec *, struct svc_req *);
#define rpc_fifo_set_level ((u_long)205)
extern  int * rpc_fifo_set_level_2(int *, CLIENT *);
extern  int * rpc_fifo_set_level_2_svc(int *, struct svc_req *);

#else /* Old Style C */ 
#define rpc_vpg_write_a32 ((u_long)1)
extern  int * rpc_vpg_write_a32_2();
extern  int * rpc_vpg_write_a32_2_svc();
#define rpc_vpg_read_a32 ((u_long)2)
extern  int * rpc_vpg_read_a32_2();
extern  int * rpc_vpg_read_a32_2_svc();
#define rpc_vpg_set_clk_divider ((u_long)3)
extern  int * rpc_vpg_set_clk_divider_2();
extern  int * rpc_vpg_set_clk_divider_2_svc();
#define rpc_vpg_set_clk_delay ((u_long)4)
extern  int * rpc_vpg_set_clk_delay_2();
extern  int * rpc_vpg_set_clk_delay_2_svc();
#define rpc_vpg_write_output ((u_long)5)
extern  int * rpc_vpg_write_output_2();
extern  int * rpc_vpg_write_output_2_svc();
#define rpc_vpg_read_input ((u_long)6)
extern  int * rpc_vpg_read_input_2();
extern  int * rpc_vpg_read_input_2_svc();
#define rpc_vpg_loadpattern ((u_long)7)
extern  int * rpc_vpg_loadpattern_2();
extern  int * rpc_vpg_loadpattern_2_svc();
#define rpc_vpg_jump ((u_long)8)
extern  int * rpc_vpg_jump_2();
extern  int * rpc_vpg_jump_2_svc();
#define rpc_vpg_clk ((u_long)9)
extern  int * rpc_vpg_clk_2();
extern  int * rpc_vpg_clk_2_svc();
#define rpc_vpg_write_status ((u_long)10)
extern  int * rpc_vpg_write_status_2();
extern  int * rpc_vpg_write_status_2_svc();
#define rpc_vpg_read_status ((u_long)11)
extern  int * rpc_vpg_read_status_2();
extern  int * rpc_vpg_read_status_2_svc();
#define rpc_vpg_set_force ((u_long)12)
extern  int * rpc_vpg_set_force_2();
extern  int * rpc_vpg_set_force_2_svc();
#define rpc_vpg_clk_start ((u_long)13)
extern  int * rpc_vpg_clk_start_2();
extern  int * rpc_vpg_clk_start_2_svc();
#define rpc_vpg_clk_stop ((u_long)14)
extern  int * rpc_vpg_clk_stop_2();
extern  int * rpc_vpg_clk_stop_2_svc();
#define rpc_vpg_pc_reset ((u_long)15)
extern  int * rpc_vpg_pc_reset_2();
extern  int * rpc_vpg_pc_reset_2_svc();
#define rpc_vpg_clr_mem ((u_long)16)
extern  int * rpc_vpg_clr_mem_2();
extern  int * rpc_vpg_clr_mem_2_svc();
#define rpc_vpg_vpgini ((u_long)17)
extern  int * rpc_vpg_vpgini_2();
extern  int * rpc_vpg_vpgini_2_svc();
#define rpc_fifo_read_d32 ((u_long)50)
extern  int * rpc_fifo_read_d32_2();
extern  int * rpc_fifo_read_d32_2_svc();
#define rpc_fifo_write_d32 ((u_long)51)
extern  int * rpc_fifo_write_d32_2();
extern  int * rpc_fifo_write_d32_2_svc();
#define rpc_fifo_fifoini ((u_long)52)
extern  int * rpc_fifo_fifoini_2();
extern  int * rpc_fifo_fifoini_2_svc();
#define rpc_fifo_read_data ((u_long)53)
extern  int * rpc_fifo_read_data_2();
extern  int * rpc_fifo_read_data_2_svc();
#define rpc_fifo_read_event_cntr ((u_long)54)
extern  int * rpc_fifo_read_event_cntr_2();
extern  int * rpc_fifo_read_event_cntr_2_svc();
#define rpc_fifo_read_status ((u_long)55)
extern  int * rpc_fifo_read_status_2();
extern  int * rpc_fifo_read_status_2_svc();
#define rpc_fifo_write_data ((u_long)56)
extern  int * rpc_fifo_write_data_2();
extern  int * rpc_fifo_write_data_2_svc();
#define rpc_fifo_write_control ((u_long)57)
extern  int * rpc_fifo_write_control_2();
extern  int * rpc_fifo_write_control_2_svc();
#define rpc_fifo_write_test ((u_long)58)
extern  int * rpc_fifo_write_test_2();
extern  int * rpc_fifo_write_test_2_svc();
#define rpc_sd_selectmodule ((u_long)101)
extern  int * rpc_sd_selectmodule_2();
extern  int * rpc_sd_selectmodule_2_svc();
#define rpc_sd_selectchip ((u_long)102)
extern  int * rpc_sd_selectchip_2();
extern  int * rpc_sd_selectchip_2_svc();
#define rpc_sd_selectstrip ((u_long)103)
extern  int * rpc_sd_selectstrip_2();
extern  int * rpc_sd_selectstrip_2_svc();
#define rpc_sd_setdac ((u_long)104)
extern  int * rpc_sd_setdac_2();
extern  int * rpc_sd_setdac_2_svc();
#define rpc_sd_reset ((u_long)105)
extern  int * rpc_sd_reset_2();
extern  int * rpc_sd_reset_2_svc();
#define rpc_sd_readmodule ((u_long)106)
extern  int * rpc_sd_readmodule_2();
extern  int * rpc_sd_readmodule_2_svc();
#define rpc_sd_readdet ((u_long)107)
extern  int * rpc_sd_readdet_2();
extern  int * rpc_sd_readdet_2_svc();
#define rpc_sd_testFPGA ((u_long)108)
extern  int * rpc_sd_testfpga_2();
extern  int * rpc_sd_testfpga_2_svc();
#define rpc_sd_teststshift ((u_long)109)
extern  int * rpc_sd_teststshift_2();
extern  int * rpc_sd_teststshift_2_svc();
#define rpc_sd_testdtshift ((u_long)110)
extern  int * rpc_sd_testdtshift_2();
extern  int * rpc_sd_testdtshift_2_svc();
#define rpc_sd_settrimbits ((u_long)111)
extern  int * rpc_sd_settrimbits_2();
extern  int * rpc_sd_settrimbits_2_svc();
#define rpc_sd_initdet ((u_long)112)
extern  int * rpc_sd_initdet_2();
extern  int * rpc_sd_initdet_2_svc();
#define rpc_sd_writest ((u_long)113)
extern  int * rpc_sd_writest_2();
extern  int * rpc_sd_writest_2_svc();
#define rpc_sd_readst ((u_long)114)
extern  int * rpc_sd_readst_2();
extern  int * rpc_sd_readst_2_svc();
#define rpc_sd_writedt ((u_long)115)
extern  int * rpc_sd_writedt_2();
extern  int * rpc_sd_writedt_2_svc();
#define rpc_sd_readdt ((u_long)116)
extern  int * rpc_sd_readdt_2();
extern  int * rpc_sd_readdt_2_svc();
#define rpc_sd_writemodFPGA ((u_long)117)
extern  int * rpc_sd_writemodfpga_2();
extern  int * rpc_sd_writemodfpga_2_svc();
#define rpc_sd_readmodFPGA ((u_long)118)
extern  int * rpc_sd_readmodfpga_2();
extern  int * rpc_sd_readmodfpga_2_svc();
#define rpc_sd_writedetFPGA ((u_long)119)
extern  int * rpc_sd_writedetfpga_2();
extern  int * rpc_sd_writedetfpga_2_svc();
#define rpc_sd_readdetFPGA ((u_long)120)
extern  int * rpc_sd_readdetfpga_2();
extern  int * rpc_sd_readdetfpga_2_svc();
#define rpc_px_read_image ((u_long)200)
extern  image * rpc_px_read_image_2();
extern  image * rpc_px_read_image_2_svc();
#define rpc_px_set_selector ((u_long)201)
extern  int * rpc_px_set_selector_2();
extern  int * rpc_px_set_selector_2_svc();
#define rpc_vpg_set_default ((u_long)202)
extern  int * rpc_vpg_set_default_2();
extern  int * rpc_vpg_set_default_2_svc();
#define rpc_fifo_write_image ((u_long)203)
extern  int * rpc_fifo_write_image_2();
extern  int * rpc_fifo_write_image_2_svc();
#define rpc_fifo_write_n_images ((u_long)204)
extern  int * rpc_fifo_write_n_images_2();
extern  int * rpc_fifo_write_n_images_2_svc();
#define rpc_fifo_set_level ((u_long)205)
extern  int * rpc_fifo_set_level_2();
extern  int * rpc_fifo_set_level_2_svc();
#endif /* Old Style C */ 

#endif /* !_IOC_RPC_H_RPCGEN */
