/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ioc_rpc.h"


void
rpcfns_2( char* host )
{
	CLIENT *clnt;
	int  *result_1;
	address  rpc_vpg_write_a32_2_arg;
	int  *result_2;
	address  rpc_vpg_read_a32_2_arg;
	int  *result_3;
	vpg  rpc_vpg_set_clk_divider_2_arg;
	int  *result_4;
	vpg  rpc_vpg_set_clk_delay_2_arg;
	int  *result_5;
	vpg  rpc_vpg_write_output_2_arg;
	int  *result_6;
	char*  rpc_vpg_read_input_2_arg;
	int  *result_7;
	vpg  rpc_vpg_loadpattern_2_arg;
	int  *result_8;
	vpg  rpc_vpg_jump_2_arg;
	int  *result_9;
	char*  rpc_vpg_clk_2_arg;
	int  *result_10;
	vpg  rpc_vpg_write_status_2_arg;
	int  *result_11;
	char*  rpc_vpg_read_status_2_arg;
	int  *result_12;
	vpg  rpc_vpg_set_force_2_arg;
	int  *result_13;
	char*  rpc_vpg_clk_start_2_arg;
	int  *result_14;
	char*  rpc_vpg_clk_stop_2_arg;
	int  *result_15;
	char*  rpc_vpg_pc_reset_2_arg;
	int  *result_16;
	char*  rpc_vpg_clr_mem_2_arg;
	int  *result_17;
	char*  rpc_vpg_vpgini_2_arg;
	int  *result_18;
	address  rpc_fifo_read_d32_2_arg;
	int  *result_19;
	address  rpc_fifo_write_d32_2_arg;
	int  *result_20;
	char*  rpc_fifo_fifoini_2_arg;
	int  *result_21;
	address  rpc_fifo_read_data_2_arg;
	int  *result_22;
	address  rpc_fifo_read_event_cntr_2_arg;
	int  *result_23;
	address  rpc_fifo_read_status_2_arg;
	int  *result_24;
	address  rpc_fifo_write_data_2_arg;
	int  *result_25;
	address  rpc_fifo_write_control_2_arg;
	int  *result_26;
	address  rpc_fifo_write_test_2_arg;
	int  *result_27;
	detector  rpc_sd_selectmodule_2_arg;
	int  *result_28;
	detector  rpc_sd_selectchip_2_arg;
	int  *result_29;
	detector  rpc_sd_selectstrip_2_arg;
	int  *result_30;
	detector  rpc_sd_setdac_2_arg;
	int  *result_31;
	detector  rpc_sd_reset_2_arg;
	int  *result_32;
	detector  rpc_sd_readmodule_2_arg;
	int  *result_33;
	detector  rpc_sd_readdet_2_arg;
	int  *result_34;
	detector  rpc_sd_testfpga_2_arg;
	int  *result_35;
	detector  rpc_sd_teststshift_2_arg;
	int  *result_36;
	detector  rpc_sd_testdtshift_2_arg;
	int  *result_37;
	detector  rpc_sd_settrimbits_2_arg;
	int  *result_38;
	detector  rpc_sd_initdet_2_arg;
	int  *result_39;
	detector  rpc_sd_writest_2_arg;
	int  *result_40;
	detector  rpc_sd_readst_2_arg;
	int  *result_41;
	detector  rpc_sd_writedt_2_arg;
	int  *result_42;
	detector  rpc_sd_readdt_2_arg;
	int  *result_43;
	detector  rpc_sd_writemodfpga_2_arg;
	int  *result_44;
	detector  rpc_sd_readmodfpga_2_arg;
	int  *result_45;
	detector  rpc_sd_writedetfpga_2_arg;
	int  *result_46;
	detector  rpc_sd_readdetfpga_2_arg;
	image  *result_47;
	char*  rpc_px_read_image_2_arg;
	int  *result_48;
	arry  rpc_px_set_selector_2_arg;
	int  *result_49;
	int  rpc_vpg_set_default_2_arg;
	int  *result_50;
	image_spec  rpc_fifo_write_image_2_arg;
	int  *result_51;
	n_image_spec  rpc_fifo_write_n_images_2_arg;
	int  *result_52;
	int  rpc_fifo_set_level_2_arg;
	clnt = clnt_create(host, rpcfns, TWO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = rpc_vpg_write_a32_2(&rpc_vpg_write_a32_2_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_2 = rpc_vpg_read_a32_2(&rpc_vpg_read_a32_2_arg, clnt);
	if (result_2 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_3 = rpc_vpg_set_clk_divider_2(&rpc_vpg_set_clk_divider_2_arg, clnt);
	if (result_3 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_4 = rpc_vpg_set_clk_delay_2(&rpc_vpg_set_clk_delay_2_arg, clnt);
	if (result_4 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_5 = rpc_vpg_write_output_2(&rpc_vpg_write_output_2_arg, clnt);
	if (result_5 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_6 = rpc_vpg_read_input_2((void*)&rpc_vpg_read_input_2_arg, clnt);
	if (result_6 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_7 = rpc_vpg_loadpattern_2(&rpc_vpg_loadpattern_2_arg, clnt);
	if (result_7 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_8 = rpc_vpg_jump_2(&rpc_vpg_jump_2_arg, clnt);
	if (result_8 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_9 = rpc_vpg_clk_2((void*)&rpc_vpg_clk_2_arg, clnt);
	if (result_9 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_10 = rpc_vpg_write_status_2(&rpc_vpg_write_status_2_arg, clnt);
	if (result_10 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_11 = rpc_vpg_read_status_2((void*)&rpc_vpg_read_status_2_arg, clnt);
	if (result_11 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_12 = rpc_vpg_set_force_2(&rpc_vpg_set_force_2_arg, clnt);
	if (result_12 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_13 = rpc_vpg_clk_start_2((void*)&rpc_vpg_clk_start_2_arg, clnt);
	if (result_13 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_14 = rpc_vpg_clk_stop_2((void*)&rpc_vpg_clk_stop_2_arg, clnt);
	if (result_14 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_15 = rpc_vpg_pc_reset_2((void*)&rpc_vpg_pc_reset_2_arg, clnt);
	if (result_15 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_16 = rpc_vpg_clr_mem_2((void*)&rpc_vpg_clr_mem_2_arg, clnt);
	if (result_16 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_17 = rpc_vpg_vpgini_2((void*)&rpc_vpg_vpgini_2_arg, clnt);
	if (result_17 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_18 = rpc_fifo_read_d32_2(&rpc_fifo_read_d32_2_arg, clnt);
	if (result_18 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_19 = rpc_fifo_write_d32_2(&rpc_fifo_write_d32_2_arg, clnt);
	if (result_19 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_20 = rpc_fifo_fifoini_2((void*)&rpc_fifo_fifoini_2_arg, clnt);
	if (result_20 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_21 = rpc_fifo_read_data_2(&rpc_fifo_read_data_2_arg, clnt);
	if (result_21 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_22 = rpc_fifo_read_event_cntr_2(&rpc_fifo_read_event_cntr_2_arg, clnt);
	if (result_22 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_23 = rpc_fifo_read_status_2(&rpc_fifo_read_status_2_arg, clnt);
	if (result_23 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_24 = rpc_fifo_write_data_2(&rpc_fifo_write_data_2_arg, clnt);
	if (result_24 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_25 = rpc_fifo_write_control_2(&rpc_fifo_write_control_2_arg, clnt);
	if (result_25 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_26 = rpc_fifo_write_test_2(&rpc_fifo_write_test_2_arg, clnt);
	if (result_26 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_27 = rpc_sd_selectmodule_2(&rpc_sd_selectmodule_2_arg, clnt);
	if (result_27 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_28 = rpc_sd_selectchip_2(&rpc_sd_selectchip_2_arg, clnt);
	if (result_28 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_29 = rpc_sd_selectstrip_2(&rpc_sd_selectstrip_2_arg, clnt);
	if (result_29 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_30 = rpc_sd_setdac_2(&rpc_sd_setdac_2_arg, clnt);
	if (result_30 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_31 = rpc_sd_reset_2(&rpc_sd_reset_2_arg, clnt);
	if (result_31 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_32 = rpc_sd_readmodule_2(&rpc_sd_readmodule_2_arg, clnt);
	if (result_32 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_33 = rpc_sd_readdet_2(&rpc_sd_readdet_2_arg, clnt);
	if (result_33 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_34 = rpc_sd_testfpga_2(&rpc_sd_testfpga_2_arg, clnt);
	if (result_34 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_35 = rpc_sd_teststshift_2(&rpc_sd_teststshift_2_arg, clnt);
	if (result_35 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_36 = rpc_sd_testdtshift_2(&rpc_sd_testdtshift_2_arg, clnt);
	if (result_36 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_37 = rpc_sd_settrimbits_2(&rpc_sd_settrimbits_2_arg, clnt);
	if (result_37 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_38 = rpc_sd_initdet_2(&rpc_sd_initdet_2_arg, clnt);
	if (result_38 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_39 = rpc_sd_writest_2(&rpc_sd_writest_2_arg, clnt);
	if (result_39 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_40 = rpc_sd_readst_2(&rpc_sd_readst_2_arg, clnt);
	if (result_40 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_41 = rpc_sd_writedt_2(&rpc_sd_writedt_2_arg, clnt);
	if (result_41 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_42 = rpc_sd_readdt_2(&rpc_sd_readdt_2_arg, clnt);
	if (result_42 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_43 = rpc_sd_writemodfpga_2(&rpc_sd_writemodfpga_2_arg, clnt);
	if (result_43 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_44 = rpc_sd_readmodfpga_2(&rpc_sd_readmodfpga_2_arg, clnt);
	if (result_44 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_45 = rpc_sd_writedetfpga_2(&rpc_sd_writedetfpga_2_arg, clnt);
	if (result_45 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_46 = rpc_sd_readdetfpga_2(&rpc_sd_readdetfpga_2_arg, clnt);
	if (result_46 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_47 = rpc_px_read_image_2((void*)&rpc_px_read_image_2_arg, clnt);
	if (result_47 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_48 = rpc_px_set_selector_2(&rpc_px_set_selector_2_arg, clnt);
	if (result_48 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_49 = rpc_vpg_set_default_2(&rpc_vpg_set_default_2_arg, clnt);
	if (result_49 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_50 = rpc_fifo_write_image_2(&rpc_fifo_write_image_2_arg, clnt);
	if (result_50 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_51 = rpc_fifo_write_n_images_2(&rpc_fifo_write_n_images_2_arg, clnt);
	if (result_51 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_52 = rpc_fifo_set_level_2(&rpc_fifo_set_level_2_arg, clnt);
	if (result_52 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	clnt_destroy( clnt );
}


main( int argc, char* argv[] )
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	rpcfns_2( host );
}
