#!/bin/sh

rpcgen ioc_rpc.x
rpcgen -Sc ioc_rpc.x >ioc_rpc_client_example.c 
rpcgen -Ss ioc_rpc.x >ioc_rpc_server_example.c 

cp ioc_rpc_xdr.c ..
cp ioc_rpc_xdr.c ../rpc_server
cp ioc_rpc_clnt.c ../rpc_clnt.c
cp ioc_rpc_svc.c ../rpc_server
cp ioc_rpc.h ../rpc_server
cp ioc_rpc.h ../../include
