/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/types.h>
#include <rpc/xdr.h>

#include "ioc_rpc.h"

bool_t
xdr_address(XDR *xdrs, address *objp)
{

//	 register long *buf;

	 if (!xdr_u_int(xdrs, &objp->addr)) {
		 return (FALSE);
	 }
	 if (!xdr_u_int(xdrs, &objp->data)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_vpg(XDR *xdrs, vpg *objp)
{

	 register long *buf;


	 if (xdrs->x_op == XDR_ENCODE) {
	 if (!xdr_string(xdrs, &objp->patname, 80)) {
		 return (FALSE);
	 }
		buf = XDR_INLINE(xdrs,5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
		 if (!xdr_u_int(xdrs, &objp->divider)) {
			 return (FALSE);
		 }
		 if (!xdr_u_int(xdrs, &objp->delay15)) {
			 return (FALSE);
		 }
		 if (!xdr_u_int(xdrs, &objp->delay16)) {
			 return (FALSE);
		 }
		 if (!xdr_u_int(xdrs, &objp->addr)) {
			 return (FALSE);
		 }
		 if (!xdr_u_int(xdrs, &objp->data)) {
			 return (FALSE);
		 }

	  }
	  else {
		 IXDR_PUT_U_LONG(buf,objp->divider);
		 IXDR_PUT_U_LONG(buf,objp->delay15);
		 IXDR_PUT_U_LONG(buf,objp->delay16);
		 IXDR_PUT_U_LONG(buf,objp->addr);
		 IXDR_PUT_U_LONG(buf,objp->data);
	  }

 	 return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
	 if (!xdr_string(xdrs, &objp->patname, 80)) {
		 return (FALSE);
	 }
		buf = XDR_INLINE(xdrs,5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
		 if (!xdr_u_int(xdrs, &objp->divider)) {
			 return (FALSE);
		 }
		 if (!xdr_u_int(xdrs, &objp->delay15)) {
			 return (FALSE);
		 }
		 if (!xdr_u_int(xdrs, &objp->delay16)) {
			 return (FALSE);
		 }
		 if (!xdr_u_int(xdrs, &objp->addr)) {
			 return (FALSE);
		 }
		 if (!xdr_u_int(xdrs, &objp->data)) {
			 return (FALSE);
		 }

	  }
	  else {
		 objp->divider = IXDR_GET_U_LONG(buf);
		 objp->delay15 = IXDR_GET_U_LONG(buf);
		 objp->delay16 = IXDR_GET_U_LONG(buf);
		 objp->addr = IXDR_GET_U_LONG(buf);
		 objp->data = IXDR_GET_U_LONG(buf);
	  }
	 return(TRUE);
	}

	 if (!xdr_string(xdrs, &objp->patname, 80)) {
		 return (FALSE);
	 }
	 if (!xdr_u_int(xdrs, &objp->divider)) {
		 return (FALSE);
	 }
	 if (!xdr_u_int(xdrs, &objp->delay15)) {
		 return (FALSE);
	 }
	 if (!xdr_u_int(xdrs, &objp->delay16)) {
		 return (FALSE);
	 }
	 if (!xdr_u_int(xdrs, &objp->addr)) {
		 return (FALSE);
	 }
	 if (!xdr_u_int(xdrs, &objp->data)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_detector(XDR *xdrs, detector *objp)
{

	 register long *buf;


	 if (xdrs->x_op == XDR_ENCODE) {
	 if (!xdr_string(xdrs, &objp->fname, 80)) {
		 return (FALSE);
	 }
		buf = XDR_INLINE(xdrs,4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
		 if (!xdr_u_int(xdrs, &objp->module)) {
			 return (FALSE);
		 }
		 if (!xdr_u_int(xdrs, &objp->chip)) {
			 return (FALSE);
		 }
		 if (!xdr_u_int(xdrs, &objp->strip)) {
			 return (FALSE);
		 }
		 if (!xdr_u_int(xdrs, &objp->data)) {
			 return (FALSE);
		 }

	  }
	  else {
		 IXDR_PUT_U_LONG(buf,objp->module);
		 IXDR_PUT_U_LONG(buf,objp->chip);
		 IXDR_PUT_U_LONG(buf,objp->strip);
		 IXDR_PUT_U_LONG(buf,objp->data);
	  }

 	 return (TRUE);
	} else if (xdrs->x_op == XDR_DECODE) {
	 if (!xdr_string(xdrs, &objp->fname, 80)) {
		 return (FALSE);
	 }
		buf = XDR_INLINE(xdrs,4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
		 if (!xdr_u_int(xdrs, &objp->module)) {
			 return (FALSE);
		 }
		 if (!xdr_u_int(xdrs, &objp->chip)) {
			 return (FALSE);
		 }
		 if (!xdr_u_int(xdrs, &objp->strip)) {
			 return (FALSE);
		 }
		 if (!xdr_u_int(xdrs, &objp->data)) {
			 return (FALSE);
		 }

	  }
	  else {
		 objp->module = IXDR_GET_U_LONG(buf);
		 objp->chip = IXDR_GET_U_LONG(buf);
		 objp->strip = IXDR_GET_U_LONG(buf);
		 objp->data = IXDR_GET_U_LONG(buf);
	  }
	 return(TRUE);
	}

	 if (!xdr_string(xdrs, &objp->fname, 80)) {
		 return (FALSE);
	 }
	 if (!xdr_u_int(xdrs, &objp->module)) {
		 return (FALSE);
	 }
	 if (!xdr_u_int(xdrs, &objp->chip)) {
		 return (FALSE);
	 }
	 if (!xdr_u_int(xdrs, &objp->strip)) {
		 return (FALSE);
	 }
	 if (!xdr_u_int(xdrs, &objp->data)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_image(XDR *xdrs, image *objp)
{

//	 register long *buf;

	 if (!xdr_int(xdrs, &objp->npix)) {
		 return (FALSE);
	 }
	 if (!xdr_array(xdrs, (char **)&objp->img.img_val, (u_int *)&objp->img.img_len, 600, sizeof(u_int), (xdrproc_t)xdr_u_int)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_arry(XDR *xdrs, arry *objp)
{

//	 register long *buf;

	 if (!xdr_array(xdrs, (char **)&objp->data.data_val, (u_int *)&objp->data.data_len, 16, sizeof(u_int), (xdrproc_t)xdr_u_int)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_image_spec(XDR *xdrs, image_spec *objp)
{

//	 register long *buf;

	 if (!xdr_string(xdrs, &objp->patname, 160)) {
		 return (FALSE);
	 }
	 if (!xdr_array(xdrs, (char **)&objp->data.data_val, (u_int *)&objp->data.data_len, 16, sizeof(u_int), (xdrproc_t)xdr_u_int)) {
		 return (FALSE);
	 }
	 if (!xdr_u_int(xdrs, &objp->mode)) {
		 return (FALSE);
	 }
	return (TRUE);
}

bool_t
xdr_n_image_spec(XDR *xdrs, n_image_spec *objp)
{

//	 register long *buf;

	 if (!xdr_string(xdrs, &objp->patname, 160)) {
		 return (FALSE);
	 }
	 if (!xdr_array(xdrs, (char **)&objp->data.data_val, (u_int *)&objp->data.data_len, 16, sizeof(u_int), (xdrproc_t)xdr_u_int)) {
		 return (FALSE);
	 }
	 if (!xdr_u_int(xdrs, &objp->nimg)) {
		 return (FALSE);
	 }
	 if (!xdr_u_int(xdrs, &objp->etime)) {
		 return (FALSE);
	 }
	return (TRUE);
}
