/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VXI11INTR_H_RPCGEN
#define _VXI11INTR_H_RPCGEN

#include <rpc/rpc.h>


struct Device_SrqParms {
	struct {
		u_int handle_len;
		char *handle_val;
	} handle;
};
typedef struct Device_SrqParms Device_SrqParms;
#ifdef __cplusplus 
extern "C" bool_t xdr_Device_SrqParms(XDR *, Device_SrqParms*);
#elif __STDC__ 
extern  bool_t xdr_Device_SrqParms(XDR *, Device_SrqParms*);
#else /* Old Style C */ 
bool_t xdr_Device_SrqParms();
#endif /* Old Style C */ 


#define DEVICE_INTR ((u_long)0x0607B1)
#define DEVICE_INTR_VERSION ((u_long)1)

#ifdef __cplusplus
#define device_intr_srq ((u_long)30)
extern "C" void * device_intr_srq_1(Device_SrqParms *, CLIENT *);
extern "C" void * device_intr_srq_1_svc(Device_SrqParms *, struct svc_req *);

#elif __STDC__
#define device_intr_srq ((u_long)30)
extern  void * device_intr_srq_1(Device_SrqParms *, CLIENT *);
extern  void * device_intr_srq_1_svc(Device_SrqParms *, struct svc_req *);

#else /* Old Style C */ 
#define device_intr_srq ((u_long)30)
extern  void * device_intr_srq_1();
extern  void * device_intr_srq_1_svc();
#endif /* Old Style C */ 

#endif /* !_VXI11INTR_H_RPCGEN */
