#!/bin/bash

loadpath=/home/efe/vxworks/FIFO/rpc_server/

rm -f *.o

./compileppc ioc_rpc_xdr
./compileppc ioc_rpc_svc
./compileppc rpcroutines
./compileppc vpg
./compileppc fifo

#cp *.o $loadpath

echo
echo "<<<<<!!!!>>>>> ---------------------------------------- <<<<<!!!!>>>>>"
echo "<<<<<!!!!>>>>> There should be 5 files in the next list <<<<<!!!!>>>>>"
echo "<<<<<!!!!>>>>> ---------------------------------------- <<<<<!!!!>>>>>"
ls -l *.o
#echo Files were copied to $loadpath
