#!/bin/sh
#
# Script to compile c-code for a PowerPC target
#
#$Author: janousch $
#$Date: 1999/10/27 12:13:37 $
#$Id: compileppc,v 1.2 1999/10/27 12:13:37 janousch Exp $
#$Name:  $
#$Revision: 1.2 $
#$Log: compileppc,v $
#Revision 1.2  1999/10/27 12:13:37  janousch
#Changed include path ${SLSBASE}/vxworks to /soft/wind since vxworks not installed under
#/devl
#
#Revision 1.1.1.1  1999/09/08 16:44:21  janousch
#Scripts for SNL- and cross-compilation
#
#
if [ $# -lt 1 ]
	then echo "error : usage compileppc filename where filename.c exists in current directory";exit
fi
/usr/local/cross/ppc/bin/ccppc $1.c -c -O2 \
-nostdinc -pedantic -fstrength-reduce  -Wall \
-fno-for-scope -DCPU_FAMILY=PPC -DCPU=PPC604 -D_GNU_TOOL -DTRUE=1 -DMV2300 \
-DvxWorks -DV5_vxWorks -fno-builtin -mstrict-align \
-I. -I/usr/local/cross/ppc/powerpc-wrs-vxworks/include  -I${SLSBASE}/include \
-DvxWorks -DV5_vxWorks
