/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ioc_rpc.h"
#include <stdio.h>
#include <stdlib.h>/* getenv, exit */
#include <rpc/pmap_clnt.h> /* for pmap_unset */
#include <string.h> /* strcmp */ 
//#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <vxWorks.h>
#include <rpcLib.h>

#ifdef __STDC__
#define SIG_PF void(*)(int)
#endif

static void
rpcfns_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		address rpc_vpg_write_a32_2_arg;
		address rpc_vpg_read_a32_2_arg;
		vpg rpc_vpg_set_clk_divider_2_arg;
		vpg rpc_vpg_set_clk_delay_2_arg;
		vpg rpc_vpg_write_output_2_arg;
		vpg rpc_vpg_loadpattern_2_arg;
		vpg rpc_vpg_jump_2_arg;
		vpg rpc_vpg_write_status_2_arg;
		vpg rpc_vpg_set_force_2_arg;
		address rpc_fifo_read_d32_2_arg;
		address rpc_fifo_write_d32_2_arg;
		address rpc_fifo_read_data_2_arg;
		address rpc_fifo_read_event_cntr_2_arg;
		address rpc_fifo_read_status_2_arg;
		address rpc_fifo_write_data_2_arg;
		address rpc_fifo_write_control_2_arg;
		address rpc_fifo_write_test_2_arg;
		detector rpc_sd_selectmodule_2_arg;
		detector rpc_sd_selectchip_2_arg;
		detector rpc_sd_selectstrip_2_arg;
		detector rpc_sd_setdac_2_arg;
		detector rpc_sd_reset_2_arg;
		detector rpc_sd_readmodule_2_arg;
		detector rpc_sd_readdet_2_arg;
		detector rpc_sd_testfpga_2_arg;
		detector rpc_sd_teststshift_2_arg;
		detector rpc_sd_testdtshift_2_arg;
		detector rpc_sd_settrimbits_2_arg;
		detector rpc_sd_initdet_2_arg;
		detector rpc_sd_writest_2_arg;
		detector rpc_sd_readst_2_arg;
		detector rpc_sd_writedt_2_arg;
		detector rpc_sd_readdt_2_arg;
		detector rpc_sd_writemodfpga_2_arg;
		detector rpc_sd_readmodfpga_2_arg;
		detector rpc_sd_writedetfpga_2_arg;
		detector rpc_sd_readdetfpga_2_arg;
		arry rpc_px_set_selector_2_arg;
		int rpc_vpg_set_default_2_arg;
		image_spec rpc_fifo_write_image_2_arg;
		n_image_spec rpc_fifo_write_n_images_2_arg;
		int rpc_fifo_set_level_2_arg;
	} argument;
	char *result;
	xdrproc_t xdr_argument, xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply(transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case rpc_vpg_write_a32:
		xdr_argument = (xdrproc_t) xdr_address;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_vpg_write_a32_2_svc;
		break;

	case rpc_vpg_read_a32:
		xdr_argument = (xdrproc_t) xdr_address;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_vpg_read_a32_2_svc;
		break;

	case rpc_vpg_set_clk_divider:
		xdr_argument = (xdrproc_t) xdr_vpg;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_vpg_set_clk_divider_2_svc;
		break;

	case rpc_vpg_set_clk_delay:
		xdr_argument = (xdrproc_t) xdr_vpg;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_vpg_set_clk_delay_2_svc;
		break;

	case rpc_vpg_write_output:
		xdr_argument = (xdrproc_t) xdr_vpg;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_vpg_write_output_2_svc;
		break;

	case rpc_vpg_read_input:
		xdr_argument = (xdrproc_t) xdr_void;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_vpg_read_input_2_svc;
		break;

	case rpc_vpg_loadpattern:
		xdr_argument = (xdrproc_t) xdr_vpg;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_vpg_loadpattern_2_svc;
		break;

	case rpc_vpg_jump:
		xdr_argument = (xdrproc_t) xdr_vpg;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_vpg_jump_2_svc;
		break;

	case rpc_vpg_clk:
		xdr_argument = (xdrproc_t) xdr_void;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_vpg_clk_2_svc;
		break;

	case rpc_vpg_write_status:
		xdr_argument = (xdrproc_t) xdr_vpg;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_vpg_write_status_2_svc;
		break;

	case rpc_vpg_read_status:
		xdr_argument = (xdrproc_t) xdr_void;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_vpg_read_status_2_svc;
		break;

	case rpc_vpg_set_force:
		xdr_argument = (xdrproc_t) xdr_vpg;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_vpg_set_force_2_svc;
		break;

	case rpc_vpg_clk_start:
		xdr_argument = (xdrproc_t) xdr_void;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_vpg_clk_start_2_svc;
		break;

	case rpc_vpg_clk_stop:
		xdr_argument = (xdrproc_t) xdr_void;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_vpg_clk_stop_2_svc;
		break;

	case rpc_vpg_pc_reset:
		xdr_argument = (xdrproc_t) xdr_void;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_vpg_pc_reset_2_svc;
		break;

	case rpc_vpg_clr_mem:
		xdr_argument = (xdrproc_t) xdr_void;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_vpg_clr_mem_2_svc;
		break;

	case rpc_vpg_vpgini:
		xdr_argument = (xdrproc_t) xdr_void;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_vpg_vpgini_2_svc;
		break;

	case rpc_fifo_read_d32:
		xdr_argument = (xdrproc_t) xdr_address;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_fifo_read_d32_2_svc;
		break;

	case rpc_fifo_write_d32:
		xdr_argument = (xdrproc_t) xdr_address;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_fifo_write_d32_2_svc;
		break;

	case rpc_fifo_fifoini:
		xdr_argument = (xdrproc_t) xdr_void;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_fifo_fifoini_2_svc;
		break;

	case rpc_fifo_read_data:
		xdr_argument = (xdrproc_t) xdr_address;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_fifo_read_data_2_svc;
		break;

	case rpc_fifo_read_event_cntr:
		xdr_argument = (xdrproc_t) xdr_address;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_fifo_read_event_cntr_2_svc;
		break;

	case rpc_fifo_read_status:
		xdr_argument = (xdrproc_t) xdr_address;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_fifo_read_status_2_svc;
		break;

	case rpc_fifo_write_data:
		xdr_argument = (xdrproc_t) xdr_address;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_fifo_write_data_2_svc;
		break;

	case rpc_fifo_write_control:
		xdr_argument = (xdrproc_t) xdr_address;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_fifo_write_control_2_svc;
		break;

	case rpc_fifo_write_test:
		xdr_argument = (xdrproc_t) xdr_address;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_fifo_write_test_2_svc;
		break;

	case rpc_sd_selectmodule:
		xdr_argument = (xdrproc_t) xdr_detector;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_sd_selectmodule_2_svc;
		break;

	case rpc_sd_selectchip:
		xdr_argument = (xdrproc_t) xdr_detector;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_sd_selectchip_2_svc;
		break;

	case rpc_sd_selectstrip:
		xdr_argument = (xdrproc_t) xdr_detector;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_sd_selectstrip_2_svc;
		break;

	case rpc_sd_setdac:
		xdr_argument = (xdrproc_t) xdr_detector;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_sd_setdac_2_svc;
		break;

	case rpc_sd_reset:
		xdr_argument = (xdrproc_t) xdr_detector;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_sd_reset_2_svc;
		break;

	case rpc_sd_readmodule:
		xdr_argument = (xdrproc_t) xdr_detector;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_sd_readmodule_2_svc;
		break;

	case rpc_sd_readdet:
		xdr_argument = (xdrproc_t) xdr_detector;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_sd_readdet_2_svc;
		break;

	case rpc_sd_testFPGA:
		xdr_argument = (xdrproc_t) xdr_detector;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_sd_testfpga_2_svc;
		break;

	case rpc_sd_teststshift:
		xdr_argument = (xdrproc_t) xdr_detector;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_sd_teststshift_2_svc;
		break;

	case rpc_sd_testdtshift:
		xdr_argument = (xdrproc_t) xdr_detector;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_sd_testdtshift_2_svc;
		break;

	case rpc_sd_settrimbits:
		xdr_argument = (xdrproc_t) xdr_detector;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_sd_settrimbits_2_svc;
		break;

	case rpc_sd_initdet:
		xdr_argument = (xdrproc_t) xdr_detector;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_sd_initdet_2_svc;
		break;

	case rpc_sd_writest:
		xdr_argument = (xdrproc_t) xdr_detector;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_sd_writest_2_svc;
		break;

	case rpc_sd_readst:
		xdr_argument = (xdrproc_t) xdr_detector;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_sd_readst_2_svc;
		break;

	case rpc_sd_writedt:
		xdr_argument = (xdrproc_t) xdr_detector;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_sd_writedt_2_svc;
		break;

	case rpc_sd_readdt:
		xdr_argument = (xdrproc_t) xdr_detector;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_sd_readdt_2_svc;
		break;

	case rpc_sd_writemodFPGA:
		xdr_argument = (xdrproc_t) xdr_detector;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_sd_writemodfpga_2_svc;
		break;

	case rpc_sd_readmodFPGA:
		xdr_argument = (xdrproc_t) xdr_detector;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_sd_readmodfpga_2_svc;
		break;

	case rpc_sd_writedetFPGA:
		xdr_argument = (xdrproc_t) xdr_detector;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_sd_writedetfpga_2_svc;
		break;

	case rpc_sd_readdetFPGA:
		xdr_argument = (xdrproc_t) xdr_detector;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_sd_readdetfpga_2_svc;
		break;

	case rpc_px_read_image:
		xdr_argument = (xdrproc_t) xdr_void;
		xdr_result = (xdrproc_t) xdr_image;
		local = (char *(*)(char *, struct svc_req *)) rpc_px_read_image_2_svc;
		break;

	case rpc_px_set_selector:
		xdr_argument = (xdrproc_t) xdr_arry;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_px_set_selector_2_svc;
		break;

	case rpc_vpg_set_default:
		xdr_argument = (xdrproc_t) xdr_int;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_vpg_set_default_2_svc;
		break;

	case rpc_fifo_write_image:
		xdr_argument = (xdrproc_t) xdr_image_spec;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_fifo_write_image_2_svc;
		break;

	case rpc_fifo_write_n_images:
		xdr_argument = (xdrproc_t) xdr_n_image_spec;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_fifo_write_n_images_2_svc;
		break;

	case rpc_fifo_set_level:
		xdr_argument = (xdrproc_t) xdr_int;
		xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) rpc_fifo_set_level_2_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, xdr_argument, (caddr_t) &argument)) {
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, xdr_result, result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, xdr_argument, (caddr_t) &argument)) {
		fprintf(stderr, "unable to free arguments");
		exit(1);
	}
	return;
}

int
rpcmain(int argc, char **argv)
{
	register SVCXPRT *transp;

	(void) rpcTaskInit();
	(void) pmap_unset(rpcfns, TWO);

	printf("Starting rpc service\n");

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf(stderr, "cannot create udp service.");
		exit(1);
	}
//	else
//		printf("UDP service created\n");

	if (!svc_register(transp, rpcfns, TWO, rpcfns_2, IPPROTO_UDP)) {
		fprintf(stderr, "unable to register (rpcfns, TWO, udp).");
		exit(1);
	}
//	else
//		printf("UDP service registered\n");

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf(stderr, "cannot create tcp service.");
		exit(1);
	}
//	else
//		printf("TCP service created\n");

	if (!svc_register(transp, rpcfns, TWO, rpcfns_2, IPPROTO_TCP)) {
		fprintf(stderr, "unable to register (rpcfns, TWO, tcp).");
		exit(1);
	}
//	else
//		printf("TCP service registered\n");

	printf("RPC successfully registered; starting service loop\n");

	svc_run();
	fprintf(stderr, "svc_run returned");
	exit(1);
	/* NOTREACHED */
return 0;
}
