/* This code can summarily replace 'main' in 
   the ioc_rpc_svc.c generated by rpcgen
*/

#include <vxWorks.h>
#include <rpcLib.h>
//#include <memory.h>

int
rpcmain(int argc, char **argv)
{
	register SVCXPRT *transp;

	(void) rpcTaskInit();
	(void) pmap_unset(rpcfns, TWO);

	printf("Starting rpc service\n");

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf(stderr, "cannot create udp service.");
		exit(1);
	}
//	else
//		printf("UDP service created\n");

	if (!svc_register(transp, rpcfns, TWO, rpcfns_2, IPPROTO_UDP)) {
		fprintf(stderr, "unable to register (rpcfns, TWO, udp).");
		exit(1);
	}
//	else
//		printf("UDP service registered\n");

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf(stderr, "cannot create tcp service.");
		exit(1);
	}
//	else
//		printf("TCP service created\n");

	if (!svc_register(transp, rpcfns, TWO, rpcfns_2, IPPROTO_TCP)) {
		fprintf(stderr, "unable to register (rpcfns, TWO, tcp).");
		exit(1);
	}
//	else
//		printf("TCP service registered\n");

	printf("RPC successfully registered; starting service loop\n");

	svc_run();
	fprintf(stderr, "svc_run returned");
	exit(1);
	/* NOTREACHED */
return 0;
}
