/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ioc.h"
#include "ioc_rpc.h"
#include <stdio.h>

int * 
rpc_vpg_write_a32_2_svc(address *argp, struct svc_req *rqstp)
{

	static int  result;

        result=vme_write_a32((*argp).addr,(*argp).data);

	return(&result);
}

int * 
rpc_vpg_read_a32_2_svc(address *argp, struct svc_req *rqstp)
{

	static int  result;

        result=vme_read_a32((*argp).addr);

	return(&result);
}

int * 
rpc_vpg_set_clk_divider_2_svc(vpg *argp, struct svc_req *rqstp)
{

	static int  result;

        result=set_clk_divider((*argp).divider);

	return(&result);
}

int * 
rpc_vpg_set_clk_delay_2_svc(vpg *argp, struct svc_req *rqstp)
{

	static int  result;

        result=set_clk_delay((*argp).delay15,(*argp).delay16);

	return(&result);
}

int * 
rpc_vpg_write_output_2_svc(vpg *argp, struct svc_req *rqstp)
{

	static int  result;

        result=write_output((*argp).data);

	return(&result);
}

int * 
rpc_vpg_read_input_2_svc(void *argp, struct svc_req *rqstp)
{

	static int  result;

        result=read_input();

	return(&result);
}

int * 
rpc_vpg_loadpattern_2_svc(vpg *argp, struct svc_req *rqstp)
{

	static int  result;

        result=loadpattern((*argp).patname);

	return(&result);
}

int * 
rpc_vpg_jump_2_svc(vpg *argp, struct svc_req *rqstp)
{

	static int  result;

        result=vme_jump((*argp).addr);

	return(&result);
}

int * 
rpc_vpg_clk_2_svc(void *argp, struct svc_req *rqstp)
{

	static int  result;

        result=vme_clk();

	return(&result);
}

int * 
rpc_vpg_write_status_2_svc(vpg *argp, struct svc_req *rqstp)
{

	static int  result;

        result=write_status((*argp).data);

	return(&result);
}

int * 
rpc_vpg_read_status_2_svc(void *argp, struct svc_req *rqstp)
{

	static int  result;

        result=read_status();

	return(&result);
}

int * 
rpc_vpg_set_force_2_svc(vpg *argp, struct svc_req *rqstp)
{

	static int  result;

        result=set_force((*argp).addr);

	return(&result);
}

int * 
rpc_vpg_clk_start_2_svc(void *argp, struct svc_req *rqstp)
{

	static int  result;

       result=clk_start();
 
	return(&result);
}

int * 
rpc_vpg_clk_stop_2_svc(void *argp, struct svc_req *rqstp)
{

	static int  result;

		result=clk_stop();

	return(&result);
}

int * 
rpc_vpg_pc_reset_2_svc(void *argp, struct svc_req *rqstp)
{

	static int  result;

		result=pc_reset();

	return(&result);
}

int * 
rpc_vpg_clr_mem_2_svc(void *argp, struct svc_req *rqstp)
{

	static int  result;

        result=clr_mem();

	return(&result);
}

int * 
rpc_vpg_vpgini_2_svc(void *argp, struct svc_req *rqstp)
{

	static int  result;

        result=vpgini();

	return(&result);
}

int * 
rpc_fifo_read_d32_2_svc(address *argp, struct svc_req *rqstp)
{

	static int  result;

		result = fifo_read_d32((*argp).addr);

	return(&result);
}

int * 
rpc_fifo_write_d32_2_svc(address *argp, struct svc_req *rqstp)
{

	static int  result;

		result = fifo_write_d32((*argp).addr, (*argp).data);

	return(&result);
}

int * 
rpc_fifo_fifoini_2_svc(void *argp, struct svc_req *rqstp)
{

	static int  result;

		result = fifoini();

	return(&result);
}

int * 
rpc_fifo_read_data_2_svc(address *argp, struct svc_req *rqstp)
{

	static int  result;

		result = fifo_read_data();

	return(&result);
}

int * 
rpc_fifo_read_event_cntr_2_svc(address *argp, struct svc_req *rqstp)
{

	static int  result;

		result = fifo_read_event_cntr();

	return(&result);
}

int * 
rpc_fifo_read_status_2_svc(address *argp, struct svc_req *rqstp)
{

	static int  result;

		result = fifo_read_status();

	return(&result);
}

int * 
rpc_fifo_write_data_2_svc(address *argp, struct svc_req *rqstp)
{

	static int  result;

		result = fifo_write_data((*argp).data);

	return(&result);
}

int * 
rpc_fifo_write_control_2_svc(address *argp, struct svc_req *rqstp)
{

	static int  result;

		result = fifo_write_control((*argp).data);

	return(&result);
}

int * 
rpc_fifo_write_test_2_svc(address *argp, struct svc_req *rqstp)
{

	static int  result;

		result = fifo_write_test((*argp).data);

	return(&result);
}

int * 
rpc_sd_selectmodule_2_svc(detector *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int * 
rpc_sd_selectchip_2_svc(detector *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int * 
rpc_sd_selectstrip_2_svc(detector *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int * 
rpc_sd_setdac_2_svc(detector *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int * 
rpc_sd_reset_2_svc(detector *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int * 
rpc_sd_readmodule_2_svc(detector *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int * 
rpc_sd_readdet_2_svc(detector *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int * 
rpc_sd_testfpga_2_svc(detector *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int * 
rpc_sd_teststshift_2_svc(detector *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int * 
rpc_sd_testdtshift_2_svc(detector *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int * 
rpc_sd_settrimbits_2_svc(detector *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int * 
rpc_sd_initdet_2_svc(detector *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int * 
rpc_sd_writest_2_svc(detector *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int * 
rpc_sd_readst_2_svc(detector *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int * 
rpc_sd_writedt_2_svc(detector *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int * 
rpc_sd_readdt_2_svc(detector *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int * 
rpc_sd_writemodfpga_2_svc(detector *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int * 
rpc_sd_readmodfpga_2_svc(detector *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int * 
rpc_sd_writedetfpga_2_svc(detector *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int * 
rpc_sd_readdetfpga_2_svc(detector *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

image * 
rpc_px_read_image_2_svc(void *argp, struct svc_req *rqstp)
{

	static int  result;
	static struct image imp;

	result = px_read_image(&(imp.img.img_len), &(imp.npix),
				&(imp.img.img_val));

	return(&imp);
}

int * 
rpc_px_set_selector_2_svc(arry *argp, struct svc_req *rqstp)
{

	static int  result;

		result = px_set_selector((*argp).data.data_len, 
					(*argp).data.data_val);

	return(&result);
}

int * 
rpc_vpg_set_default_2_svc(int *argp, struct svc_req *rqstp)
{

	static int  result;
	
		result = set_default_vpg(*argp);


	return(&result);
}

int * 
rpc_fifo_write_image_2_svc(image_spec *argp, struct svc_req *rqstp)
{

	static int  result;

		result = fifo_write_image( (*argp).patname, (*argp).data.data_len,
								(*argp).data.data_val, (*argp).mode );

	return(&result);
}

int * 
rpc_fifo_write_n_images_2_svc(n_image_spec *argp, struct svc_req *rqstp)
{

	static int  result;

		result = fifo_write_n_images( (*argp).patname, (*argp).data.data_len, 
					(*argp).data.data_val, (*argp).nimg, (*argp).etime );

	return(&result);
}

int * 
rpc_fifo_set_level_2_svc(int *argp, struct svc_req *rqstp)
{

	static int  result;

		result = fifo_set_level(*argp);

	return(&result);
}
