/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "vxi11core.h"
#include <stdio.h>
#include <stdlib.h>/* getenv, exit */
#include <rpc/pmap_clnt.h> /* for pmap_unset */
#include <string.h> /* strcmp */ 
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifdef __STDC__
#define SIG_PF void(*)(int)
#endif

static void
device_async_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		Device_Link device_abort_1_arg;
	} argument;
	char *result;
	xdrproc_t xdr_argument, xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply(transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case device_abort:
		xdr_argument = (xdrproc_t) xdr_Device_Link;
		xdr_result = (xdrproc_t) xdr_Device_Error;
		local = (char *(*)(char *, struct svc_req *)) device_abort_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, xdr_argument, (caddr_t) &argument)) {
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, xdr_result, result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, xdr_argument, (caddr_t) &argument)) {
		fprintf(stderr, "unable to free arguments");
		exit(1);
	}
	return;
}

static void
device_core_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		Create_LinkParms create_link_1_arg;
		Device_WriteParms device_write_1_arg;
		Device_ReadParms device_read_1_arg;
		Device_GenericParms device_readstb_1_arg;
		Device_GenericParms device_trigger_1_arg;
		Device_GenericParms device_clear_1_arg;
		Device_GenericParms device_remote_1_arg;
		Device_GenericParms device_local_1_arg;
		Device_LockParms device_lock_1_arg;
		Device_Link device_unlock_1_arg;
		Device_EnableSrqParms device_enable_srq_1_arg;
		Device_DocmdParms device_docmd_1_arg;
		Device_Link destroy_link_1_arg;
		Device_RemoteFunc create_intr_chan_1_arg;
	} argument;
	char *result;
	xdrproc_t xdr_argument, xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply(transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case create_link:
		xdr_argument = (xdrproc_t) xdr_Create_LinkParms;
		xdr_result = (xdrproc_t) xdr_Create_LinkResp;
		local = (char *(*)(char *, struct svc_req *)) create_link_1_svc;
		break;

	case device_write:
		xdr_argument = (xdrproc_t) xdr_Device_WriteParms;
		xdr_result = (xdrproc_t) xdr_Device_WriteResp;
		local = (char *(*)(char *, struct svc_req *)) device_write_1_svc;
		break;

	case device_read:
		xdr_argument = (xdrproc_t) xdr_Device_ReadParms;
		xdr_result = (xdrproc_t) xdr_Device_ReadResp;
		local = (char *(*)(char *, struct svc_req *)) device_read_1_svc;
		break;

	case device_readstb:
		xdr_argument = (xdrproc_t) xdr_Device_GenericParms;
		xdr_result = (xdrproc_t) xdr_Device_ReadStbResp;
		local = (char *(*)(char *, struct svc_req *)) device_readstb_1_svc;
		break;

	case device_trigger:
		xdr_argument = (xdrproc_t) xdr_Device_GenericParms;
		xdr_result = (xdrproc_t) xdr_Device_Error;
		local = (char *(*)(char *, struct svc_req *)) device_trigger_1_svc;
		break;

	case device_clear:
		xdr_argument = (xdrproc_t) xdr_Device_GenericParms;
		xdr_result = (xdrproc_t) xdr_Device_Error;
		local = (char *(*)(char *, struct svc_req *)) device_clear_1_svc;
		break;

	case device_remote:
		xdr_argument = (xdrproc_t) xdr_Device_GenericParms;
		xdr_result = (xdrproc_t) xdr_Device_Error;
		local = (char *(*)(char *, struct svc_req *)) device_remote_1_svc;
		break;

	case device_local:
		xdr_argument = (xdrproc_t) xdr_Device_GenericParms;
		xdr_result = (xdrproc_t) xdr_Device_Error;
		local = (char *(*)(char *, struct svc_req *)) device_local_1_svc;
		break;

	case device_lock:
		xdr_argument = (xdrproc_t) xdr_Device_LockParms;
		xdr_result = (xdrproc_t) xdr_Device_Error;
		local = (char *(*)(char *, struct svc_req *)) device_lock_1_svc;
		break;

	case device_unlock:
		xdr_argument = (xdrproc_t) xdr_Device_Link;
		xdr_result = (xdrproc_t) xdr_Device_Error;
		local = (char *(*)(char *, struct svc_req *)) device_unlock_1_svc;
		break;

	case device_enable_srq:
		xdr_argument = (xdrproc_t) xdr_Device_EnableSrqParms;
		xdr_result = (xdrproc_t) xdr_Device_Error;
		local = (char *(*)(char *, struct svc_req *)) device_enable_srq_1_svc;
		break;

	case device_docmd:
		xdr_argument = (xdrproc_t) xdr_Device_DocmdParms;
		xdr_result = (xdrproc_t) xdr_Device_DocmdResp;
		local = (char *(*)(char *, struct svc_req *)) device_docmd_1_svc;
		break;

	case destroy_link:
		xdr_argument = (xdrproc_t) xdr_Device_Link;
		xdr_result = (xdrproc_t) xdr_Device_Error;
		local = (char *(*)(char *, struct svc_req *)) destroy_link_1_svc;
		break;

	case create_intr_chan:
		xdr_argument = (xdrproc_t) xdr_Device_RemoteFunc;
		xdr_result = (xdrproc_t) xdr_Device_Error;
		local = (char *(*)(char *, struct svc_req *)) create_intr_chan_1_svc;
		break;

	case destroy_intr_chan:
		xdr_argument = (xdrproc_t) xdr_void;
		xdr_result = (xdrproc_t) xdr_Device_Error;
		local = (char *(*)(char *, struct svc_req *)) destroy_intr_chan_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, xdr_argument, (caddr_t) &argument)) {
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, xdr_result, result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, xdr_argument, (caddr_t) &argument)) {
		fprintf(stderr, "unable to free arguments");
		exit(1);
	}
	return;
}

int
main(int argc, char **argv)
{
	register SVCXPRT *transp;

	(void) pmap_unset(DEVICE_ASYNC, DEVICE_ASYNC_VERSION);
	(void) pmap_unset(DEVICE_CORE, DEVICE_CORE_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf(stderr, "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, DEVICE_ASYNC, DEVICE_ASYNC_VERSION, device_async_1, IPPROTO_UDP)) {
		fprintf(stderr, "unable to register (DEVICE_ASYNC, DEVICE_ASYNC_VERSION, udp).");
		exit(1);
	}
	if (!svc_register(transp, DEVICE_CORE, DEVICE_CORE_VERSION, device_core_1, IPPROTO_UDP)) {
		fprintf(stderr, "unable to register (DEVICE_CORE, DEVICE_CORE_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf(stderr, "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, DEVICE_ASYNC, DEVICE_ASYNC_VERSION, device_async_1, IPPROTO_TCP)) {
		fprintf(stderr, "unable to register (DEVICE_ASYNC, DEVICE_ASYNC_VERSION, tcp).");
		exit(1);
	}
	if (!svc_register(transp, DEVICE_CORE, DEVICE_CORE_VERSION, device_core_1, IPPROTO_TCP)) {
		fprintf(stderr, "unable to register (DEVICE_CORE, DEVICE_CORE_VERSION, tcp).");
		exit(1);
	}

	svc_run();
	fprintf(stderr, "svc_run returned");
	exit(1);
	/* NOTREACHED */
}
