/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/types.h>
#include <rpc/xdr.h>

#include "vxi11intr.h"

bool_t
xdr_Device_SrqParms(XDR *xdrs, Device_SrqParms *objp)
{

	 register long *buf;

	 if (!xdr_bytes(xdrs, (char **)&objp->handle.handle_val, (u_int *)&objp->handle.handle_len, ~0)) {
		 return (FALSE);
	 }
	return (TRUE);
}
