/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "vxi11intr.h"

void * 
device_intr_srq_1_svc(Device_SrqParms *argp, struct svc_req *rqstp)
{

	static char* result;

	/*
	 * insert server code here
	 */

	return((void*) &result);
}
