/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "vxi11intr.h"


void
device_intr_1( char* host )
{
	CLIENT *clnt;
	void  *result_1;
	Device_SrqParms  device_intr_srq_1_arg;
	clnt = clnt_create(host, DEVICE_INTR, DEVICE_INTR_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = device_intr_srq_1(&device_intr_srq_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	clnt_destroy( clnt );
}


main( int argc, char* argv[] )
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	device_intr_1( host );
}
